### PR TITLE
Improve site design

### PR DESCRIPTION
**Pull request by SantosGuillamot**
We got awesome feedback to improve the UI of the current site, so I'm opening this pull request to address that feedback.

#### Homepage

index-design

#### Movie page

movie-design

#### Actor page

actor-design

----
## Tasks

In order to achieve this, I tried to divide it into tasks. They seem a lot, but most of them are pretty easy.

#### Site
- [x] Review the colors.
- [x] Change empty "heart" icon.
- [x] Add styles to `theme.json`.

#### Header

- [x] Remove the Movies and Actors links.
- [x] Center the search and make it wider.
- [x] Change the Title styling and add the icon.
- [x] Add background with opacity to the nav bar.
- [x] Include the movies/actors background in the header.
- [x] Update the template part with all these changes.

#### Index
- [x] Add the title and the subheading.
- [x] Add border-radius to images.

#### Movie page
- [x] Remove the background image (it will be moved to the header).
- [x] Add spacer to move the content down.
- [x] Add Play Trailer button below the image.
- [x] Add Like button below the image.
- [x] Move the data table to the left column and remove most of the properties.
- [x] Change date format and move it to the subheading row.
- [x] Move time to the subheading row.
- [x] Move genres to the subheading row.
- [x] Move cast to the second column.
- [x] Make cast names smaller.
- [x] Make movie image smaller and add some radius.
- [x] Update the template part with all these changes.
- [x] Fix issue with the score.

#### Actor page
- [x] Move movies to the right column.
- [x] Make the names smaller.
- [x] Add some properties if we can.
- [x] Update the template part with all these changes.

### CODE REVIEW

**Comment by SantosGuillamot** [comment]
So far, I've moved the background image to the header using a new `page-background` block that, depending if it is a movie page or an actor, it displays different things in the background.

Apart from that, I removed the current `movie-background` blocks, updated the template-parts, and added a spacer to the movie content.

This is how it is looking so far:

#### Movie page
Screenshot 2023-03-14 at 14 36 32


#### Actor page
Screenshot 2023-03-14 at 14 36 47

**Comment by SantosGuillamot** [comment]
I've made more changes and the movie pages are almost finished. This is how it is going so far:

Screenshot 2023-03-15 at 14 35 21

**Comment by SantosGuillamot** [comment]
Okay, I believe I've covered most of the redesign:

#### Homepage

Screenshot 2023-03-15 at 17 15 22

#### Movie page

Screenshot 2023-03-15 at 17 03 20

#### Actor page

Screenshot 2023-03-15 at 17 03 33

#### Search page

In this one, I incidentally kept the movie background, but now I don't know what is better 😄 . We have two options:

**_Option 1 - With the movie background_**

Screenshot 2023-03-15 at 17 02 48

**_Option 12- Without the movie background_**
Screenshot 2023-03-15 at 17 05 16

**Comment by luisherranz** [comment]
I think it looks cool when you've ended up searching, but it's a bit crazy on the eyes when you are searching and constantly changes. I would remove it 😄

**Comment by michalczaplinski** [comment]
Yeah I agree with Luis here 🙂 

I've removed the background image on the Search page and also made the Header fixed to the top as you scroll.

**Comment by luisherranz** [comment]
Can we merge this PR?

**Comment by luisherranz** [comment]
@SantosGuillamot @michalczaplinski I'm going to merge this. Please open other PRs

**Pull request merged**
